# Generated by Django 5.1.7 on 2025-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=4),
        ),
    ]
